### ISSUE TITLE
Make this available on Nuget

### ISSUE THREAD

**Issue by madSimonJ** [madSimonJ/CSharpHacks#2]
I'd like to put this on Nuget, need to investigate how to do it & then make the necessary arrangements

**Comment by ktos** [comment]
It won't be that complicated to put this on Nuget - for starters you only need to specify a few additional fields in .csproj (and probably move from `netcoreapp` to `netstandard`).

Then just `dotnet pack` and you get your nupkg to submit :)

I think I can prepare a basic PR with necessary changes later today.

**Comment by madSimonJ** [comment]
Thanks!
